### ISSUE TITLE
yarn publish:deck fails

### ISSUE THREAD

**Issue by jaburcodes** [sibelius/relay-modern-course#4]
yarn run v1.12.3
$ yarn build && yarn copy:static && gh-pages -d dist
$ mdx-deck build src/deck.mdx
[mdx-deck] building
[mdx-deck] rendering static html
webpack:///../node_modules/mdx-deck/dist/entry.js?:65
var mod = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '/Users/jabur/foton/relay-modern-course/src/deck.mdx'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                                                              ^

Error: Cannot find module '/Users/jabur/foton/relay-modern-course/src/deck.mdx'
    at webpackMissingModule (webpack:///../node_modules/mdx-deck/dist/entry.js?:65:75)
    at eval (webpack:///../node_modules/mdx-deck/dist/entry.js?:65:201)
    at Object.../node_modules/mdx-deck/dist/entry.js (/Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:371:1)
    at __webpack_require__ (/Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:30:30)
    at /Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:94:18
    at /Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:97:10
    at webpackUniversalModuleDefinition (/Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:3:20)
    at Object.<anonymous> (/Users/jabur/foton/relay-modern-course/dist/TEMP/App.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
error Command failed with exit code 1.

**Comment by sibelius** [comment]
we need to move to monorepo first 

check #1 

there is many decks in the same package

publish:deck only works on single file
